/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingsystem.UserInterface;

import parkingsystem.BusinessLogic.Inventory;
import parkingsystem.BusinessLogic.ParkingLot;
import parkingsystem.BusinessLogic.Vehicle;
import parkingsystem.Enums.VehicleTypes;
import parkingsystem.Utility.FormUtility;
import parkingsystem.Utility.ParkingLotUtil;
import parkingsystem.Utility.TimeFormatting;
import parkingsystem.Utility.VehicleUtil;

import javax.swing.*;
import java.sql.Time;
import java.sql.Timestamp;

/**
 *
 * @author talha
 */
public class PaymentReceiptFrame extends javax.swing.JFrame {

    /**
     * Creates new form PaymentReceiptFrame
     */
    public PaymentReceiptFrame(Inventory inventory, float payedAmount) {
        VehicleUtil vehicleUtil = new VehicleUtil();
        ParkingLotUtil plUtil = new ParkingLotUtil();

        int vehicleId = inventory.getVehicleId();
        int parkingLotId = inventory.getParkingLotId();
        Timestamp timeEntrance = inventory.getTimeEntrance();
        Timestamp timeExit = inventory.getTimeExit();
        String timeEntranceStr = TimeFormatting.getDateTimeString(timeEntrance);
        String timeExitStr = TimeFormatting.getDateTimeString(timeExit);
        Vehicle vehicle = vehicleUtil.getVehicleWithId(vehicleId);
        String regNumber = vehicle.getRegNumber();
        String vehicleName = vehicle.getVehicleName();
        int vehicleTypeValue = vehicle.getVehicleType();
        String vehicleTypeName = VehicleTypes.getNameFromValue(vehicleTypeValue);
        String ownerName = vehicle.getOwnerName();
        ParkingLot parkingLot = plUtil.getParkingLotFromId(parkingLotId);
        float parkingFee = parkingLot.getSingleParkingFee(vehicleTypeValue);
        String parkingFeeStr = "Rs " + parkingFee + " (Per Hour)";
        float totalFee = inventory.getTotalFee();
        String totalFeeStr = "Rs " + totalFee;
        String payedAmountStr = "Rs " + payedAmount;
        String changeAmount = "Nil";
        if(payedAmount > totalFee){
            changeAmount = "Rs " + (payedAmount - totalFee);
        }


        initComponents();

        lbCustomerName.setText(ownerName.isBlank()? "Nil": ownerName);
        lbRegNumber.setText(regNumber);
        lbEntranceTime.setText(timeEntranceStr);
        lbExitTime.setText(timeExitStr);
        lbVehicleName.setText(vehicleName);
        lbVehicleType.setText(vehicleTypeName);
        lbParkingFee.setText(parkingFeeStr);
        lbTotalFee.setText(totalFeeStr);
        lbAmountPayed.setText(payedAmountStr);
        lbChangeAmount.setText(changeAmount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnPaymentReceipt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbCustomerName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbEntranceTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbExitTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbRegNumber = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbVehicleName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbVehicleType = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbParkingFee = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbTotalFee = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbAmountPayed = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbChangeAmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        pnPaymentReceipt.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Payment Receipt");

        jLabel3.setText("Customer Name");

        lbCustomerName.setText("lbCustomerName");

        jLabel4.setText("Entrance Time");

        lbEntranceTime.setText("lbEntranceTime");

        jLabel5.setText("Exit Time");

        lbExitTime.setText("lbExitTime");

        jLabel6.setText("Registration Number");

        lbRegNumber.setText("lbRegNumber");

        jLabel7.setText("Vehicle Name");

        lbVehicleName.setText("lbVehicleName");

        jLabel8.setText("Vehicle Type");

        lbVehicleType.setText("lbVehicleType");

        jLabel9.setText("Parking Fee");

        lbParkingFee.setText("lbParkingFee");

        jLabel10.setText("Total Fee");

        lbTotalFee.setText("lbTotalFee");

        jLabel11.setText("Amount Payed");

        lbAmountPayed.setText("lbAmountPayed");

        jLabel12.setText("Change Amount");

        lbChangeAmount.setText("lbChangeAmount");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel2.setText("Vehicle Details");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel13.setText("Payment Details");

        javax.swing.GroupLayout pnPaymentReceiptLayout = new javax.swing.GroupLayout(pnPaymentReceipt);
        pnPaymentReceipt.setLayout(pnPaymentReceiptLayout);
        pnPaymentReceiptLayout.setHorizontalGroup(
            pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaymentReceiptLayout.createSequentialGroup()
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPaymentReceiptLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(pnPaymentReceiptLayout.createSequentialGroup()
                                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCustomerName)
                                    .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbExitTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbEntranceTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbVehicleType)
                                    .addComponent(lbParkingFee)
                                    .addComponent(lbTotalFee)
                                    .addComponent(lbAmountPayed)
                                    .addComponent(lbChangeAmount)
                                    .addComponent(lbVehicleName)
                                    .addComponent(lbRegNumber)))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(pnPaymentReceiptLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnPaymentReceiptLayout.setVerticalGroup(
            pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPaymentReceiptLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbCustomerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbEntranceTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbExitTime))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbRegNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbVehicleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lbVehicleType))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbParkingFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbTotalFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbAmountPayed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPaymentReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbChangeAmount))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnClose))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPaymentReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(pnPaymentReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        FormUtility.printPanel(pnPaymentReceipt);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAmountPayed;
    private javax.swing.JLabel lbChangeAmount;
    private javax.swing.JLabel lbCustomerName;
    private javax.swing.JLabel lbEntranceTime;
    private javax.swing.JLabel lbExitTime;
    private javax.swing.JLabel lbParkingFee;
    private javax.swing.JLabel lbRegNumber;
    private javax.swing.JLabel lbTotalFee;
    private javax.swing.JLabel lbVehicleName;
    private javax.swing.JLabel lbVehicleType;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnPaymentReceipt;
    // End of variables declaration//GEN-END:variables
}
